services:
  auth:
    build:
      context: .
      dockerfile: auth.dockerfile
    environment:
      TOKEN_KEY: "shouldbeverysecure"
      AUTH_SERVER_PORT: "3000"
      COMMUNICATION_PROTOCOL: "gRPC"
    deploy:
      mode: replicated
      replicas: 4
  users:
    depends_on:
      - auth
    build:
      context: .
      dockerfile: users.dockerfile
    ports:
      - "3001:3001"
    environment:
      AUTH_API_ADDRESS: "dns:///auth:3000"
      USERS_SERVER_PORT: "3001"
      COMMUNICATION_PROTOCOL: "gRPC"
      MONGODB_CONNECTION_URI: ${MONGODB_CONNECTION_URI}
