services:
  auth:
    build:
      context: .
      dockerfile: auth.dockerfile
    environment:
      TOKEN_KEY: "shouldbeverysecure"
      AUTH_SERVER_PORT: "3000"
      COMMUNICATION_PROTOCOL: "gRPC"
  users:
    depends_on:
      - auth
    build:
      context: .
      dockerfile: users.dockerfile
    ports:
      - "3001:3001"
    environment:
      MONGODB_CONNECTION_URI: ${MONGODB_CONNECTION_URI}
      AUTH_API_ADDRESS: "http://auth:3000"
      USERS_SERVER_PORT: "3001"
      COMMUNICATION_PROTOCOL: "gRPC"
