apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-api
          image: eduartepaiva/kub-dep-auth:latest
          imagePullPolicy: Always
          env:
            - name: TOKEN_KEY
              value: "shouldbeverysecure"
            - name: AUTH_SERVER_PORT
              value: "50051"
            - name: COMMUNICATION_PROTOCOL
              value: gRPC
