// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: api/kam.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHashedPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHashedPasswordReq) Reset() {
	*x = GetHashedPasswordReq{}
	mi := &file_api_kam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashedPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashedPasswordReq) ProtoMessage() {}

func (x *GetHashedPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_kam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashedPasswordReq.ProtoReflect.Descriptor instead.
func (*GetHashedPasswordReq) Descriptor() ([]byte, []int) {
	return file_api_kam_proto_rawDescGZIP(), []int{0}
}

func (x *GetHashedPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetHashedPasswordRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HashedPassword string                 `protobuf:"bytes,1,opt,name=HashedPassword,proto3" json:"HashedPassword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHashedPasswordRes) Reset() {
	*x = GetHashedPasswordRes{}
	mi := &file_api_kam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHashedPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHashedPasswordRes) ProtoMessage() {}

func (x *GetHashedPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_kam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHashedPasswordRes.ProtoReflect.Descriptor instead.
func (*GetHashedPasswordRes) Descriptor() ([]byte, []int) {
	return file_api_kam_proto_rawDescGZIP(), []int{1}
}

func (x *GetHashedPasswordRes) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

type GetTokenReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Password       string                 `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	HashedPassword string                 `protobuf:"bytes,2,opt,name=HashedPassword,proto3" json:"HashedPassword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTokenReq) Reset() {
	*x = GetTokenReq{}
	mi := &file_api_kam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenReq) ProtoMessage() {}

func (x *GetTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_kam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenReq.ProtoReflect.Descriptor instead.
func (*GetTokenReq) Descriptor() ([]byte, []int) {
	return file_api_kam_proto_rawDescGZIP(), []int{2}
}

func (x *GetTokenReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetTokenReq) GetHashedPassword() string {
	if x != nil {
		return x.HashedPassword
	}
	return ""
}

type GetTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRes) Reset() {
	*x = GetTokenRes{}
	mi := &file_api_kam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRes) ProtoMessage() {}

func (x *GetTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_kam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRes.ProtoReflect.Descriptor instead.
func (*GetTokenRes) Descriptor() ([]byte, []int) {
	return file_api_kam_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetTokenConfirmationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenConfirmationReq) Reset() {
	*x = GetTokenConfirmationReq{}
	mi := &file_api_kam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenConfirmationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenConfirmationReq) ProtoMessage() {}

func (x *GetTokenConfirmationReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_kam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenConfirmationReq.ProtoReflect.Descriptor instead.
func (*GetTokenConfirmationReq) Descriptor() ([]byte, []int) {
	return file_api_kam_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenConfirmationReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetTokenConfirmationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenConfirmationRes) Reset() {
	*x = GetTokenConfirmationRes{}
	mi := &file_api_kam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenConfirmationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenConfirmationRes) ProtoMessage() {}

func (x *GetTokenConfirmationRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_kam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenConfirmationRes.ProtoReflect.Descriptor instead.
func (*GetTokenConfirmationRes) Descriptor() ([]byte, []int) {
	return file_api_kam_proto_rawDescGZIP(), []int{5}
}

func (x *GetTokenConfirmationRes) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_api_kam_proto protoreflect.FileDescriptor

var file_api_kam_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65,
	0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3e, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x26, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x51, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x23, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x33, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x49, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49,
	0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x32, 0xdc, 0x01, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x52, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x64, 0x75, 0x61, 0x72, 0x74, 0x65, 0x50, 0x61, 0x69, 0x76, 0x61,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2d, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_kam_proto_rawDescOnce sync.Once
	file_api_kam_proto_rawDescData []byte
)

func file_api_kam_proto_rawDescGZIP() []byte {
	file_api_kam_proto_rawDescOnce.Do(func() {
		file_api_kam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kam_proto_rawDesc), len(file_api_kam_proto_rawDesc)))
	})
	return file_api_kam_proto_rawDescData
}

var file_api_kam_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_kam_proto_goTypes = []any{
	(*GetHashedPasswordReq)(nil),    // 0: api.GetHashedPasswordReq
	(*GetHashedPasswordRes)(nil),    // 1: api.GetHashedPasswordRes
	(*GetTokenReq)(nil),             // 2: api.GetTokenReq
	(*GetTokenRes)(nil),             // 3: api.GetTokenRes
	(*GetTokenConfirmationReq)(nil), // 4: api.GetTokenConfirmationReq
	(*GetTokenConfirmationRes)(nil), // 5: api.GetTokenConfirmationRes
}
var file_api_kam_proto_depIdxs = []int32{
	0, // 0: api.authService.GetHashedPassword:input_type -> api.GetHashedPasswordReq
	2, // 1: api.authService.GetToken:input_type -> api.GetTokenReq
	4, // 2: api.authService.GetTokenConfirmation:input_type -> api.GetTokenConfirmationReq
	1, // 3: api.authService.GetHashedPassword:output_type -> api.GetHashedPasswordRes
	3, // 4: api.authService.GetToken:output_type -> api.GetTokenRes
	5, // 5: api.authService.GetTokenConfirmation:output_type -> api.GetTokenConfirmationRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kam_proto_init() }
func file_api_kam_proto_init() {
	if File_api_kam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kam_proto_rawDesc), len(file_api_kam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kam_proto_goTypes,
		DependencyIndexes: file_api_kam_proto_depIdxs,
		MessageInfos:      file_api_kam_proto_msgTypes,
	}.Build()
	File_api_kam_proto = out.File
	file_api_kam_proto_goTypes = nil
	file_api_kam_proto_depIdxs = nil
}
